project:
  type: website

execute: 
  freeze: auto
website:
  title: "Soumya M"
  favicon: /img/Sm_logo.png
  search: false
  navbar:
    logo: /img/Sm_logo.png

    left:
      - href: index.qmd
        text: HOME
      - text: PROJECTS
        href: projects.qmd
      - text: BLOG
        href: blog.qmd
      - text: USEFUL
        href: useful.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    


