project:
  type: website

website:
  title: "Soumya M"
  favicon: /img/Sm_logo.png
  search: false
  navbar:
    logo: /img/Sm_logo.png

    left:
      - href: index.qmd
        text: Home
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
      - text: Useful
        href: useful.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    


